//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupLemmatizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LookupLemmatizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abades	abá
        ///abadesa	abá
        ///abadeses	abá
        ///ababayada	ababayáu
        ///ababayaes	ababayáu
        ///ababayao	ababayáu
        ///ababayaos	ababayáu
        ///abacelera	abacelerar
        ///abaceleraba	abacelerar
        ///abacelerabais	abacelerar
        ///abacelerábamos	abacelerar
        ///abacelerabeis	abacelerar
        ///abacelerábemos	abacelerar
        ///abaceleraben	abacelerar
        ///abacelerabes	abacelerar
        ///abacelerada	abacelerar
        ///abaceleraes	abacelerar
        ///abacelerái	abacelerar
        ///abaceleráis	abacelerar
        ///abaceleramos	abacelerar
        ///abaceleran	abacelerar
        ///abacelerando	abacelerar
        ///abacelerao	abacelerar
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ast {
            get {
                return ResourceManager.GetString("manual_lemmatization_ast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to абоната	абонат
        ///абонати	абонат
        ///абонатите	абонат
        ///абонирахме	абонирам
        ///абревиатури	абревиатура
        ///абревиатурните	абревиатурен
        ///абсолютна	абсолютен
        ///абсолютната	абсолютен
        ///абсолютния	абсолютен
        ///абсолютно	абсолютен
        ///абсолютното	абсолютен
        ///абстрактни	абстрактен
        ///абстрактно	абстрактен
        ///абсурда	абсурд
        ///абсурдна	абсурден
        ///абсурдни	абсурден
        ///абсурдния	абсурден
        ///авангарда	авангард
        ///авангардни	авангарден
        ///авангардните	авангарден
        ///авангардистите	авангардист
        ///авансово	авансов
        ///авансовото	авансов
        ///авантажа	авантаж
        ///авант [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_bg {
            get {
                return ResourceManager.GetString("manual_lemmatization_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as	a
        ///àbacs	àbac
        ///abacàs	abacà
        ///abacallan	abacallanar
        ///abacallana	abacallanar
        ///abacallanà	abacallanar
        ///abacallanada	abacallanar
        ///abacallanades	abacallanar
        ///abacallanam	abacallanar
        ///abacallanant	abacallanar
        ///abacallanara	abacallanar
        ///abacallanarà	abacallanar
        ///abacallanaran	abacallanar
        ///abacallanaràs	abacallanar
        ///abacallanaré	abacallanar
        ///abacallanarem	abacallanar
        ///abacallanàrem	abacallanar
        ///abacallanaren	abacallanar
        ///abacallanares	abacallanar
        ///abacallanareu	abacallanar
        ///abacallanàreu	abacallanar
        ///abacallanar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ca {
            get {
                return ResourceManager.GetString("manual_lemmatization_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aachenu	Aachen
        ///Aaronsona	Aaronson
        ///Aby	Aba
        ///abecedu	abeceda
        ///abecedním	abecední
        ///Abimelecha	Abimelech
        ///abonenta	abonent
        ///Abrahámu	Abrahám
        ///absencí	absence
        ///absentovala	absentovat
        ///absolutismu	absolutismus
        ///absolutistickou	absolutistický
        ///absolutního	absolutní
        ///absolutním	absolutní
        ///absolutními	absolutní
        ///absolutně	absolutno
        ///absolventi	absolvent
        ///absolventům	absolvent
        ///absurdity	absurdita
        ///nejabsurdnějších	absurdní
        ///abych	aby
        ///abychom	aby
        ///abys	aby
        ///abyste	aby
        ///Accolu	Accola
        ///achátové	achátový
        ///Achilla	Ach [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_cs {
            get {
                return ResourceManager.GetString("manual_lemmatization_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ac	a
        ///ag	a
        ///ag	â
        ///hab	ab
        ///abaci	abacws
        ///abadau	abad
        ///habadau	abad
        ///abatai	abaty
        ///aberoedd	aber
        ///haber	aber
        ///aberthau	aberth
        ///haberth	aberth
        ///abertha	aberthu
        ///aberthaf	aberthu
        ///aberthai	aberthu
        ///aberthais	aberthu
        ///aberthaist	aberthu
        ///aberthant	aberthu
        ///aberthasai	aberthu
        ///aberthasant	aberthu
        ///aberthasech	aberthu
        ///aberthasem	aberthu
        ///aberthasent	aberthu
        ///aberthasid	aberthu
        ///aberthasit	aberthu
        ///aberthasoch	aberthu
        ///aberthasom	aberthu
        ///aberthaswn	aberthu
        ///aberthech	aberthu
        ///aberthed	aberthu
        ///aberthem	aberthu
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_cy {
            get {
                return ResourceManager.GetString("manual_lemmatization_cy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As	A
        ///Aachens	Aachen
        ///Aale	Aal
        ///Aalen	Aal
        ///Aales	Aal
        ///Aals	Aal
        ///Aal	aalen
        ///Aale	aalen
        ///aalend	aalen
        ///Aalens	Aalen
        ///aalest	aalen
        ///aalet	aalen
        ///aalst	aalen
        ///aalt	aalen
        ///aalte	aalen
        ///aalten	aalen
        ///aaltest	aalen
        ///aaltet	aalen
        ///geaalt	aalen
        ///aalende	aalend
        ///aalendem	aalend
        ///aalenden	aalend
        ///aalender	aalend
        ///aalendere	aalend
        ///aalenderem	aalend
        ///aalenderen	aalend
        ///aalenderer	aalend
        ///aalenderes	aalend
        ///aalendes	aalend
        ///aalendste	aalend
        ///aalendstem	aalend
        ///aalendsten	aalend
        ///aalendster	aalend
        ///aalendstes	aalend
        ///Aal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_de {
            get {
                return ResourceManager.GetString("manual_lemmatization_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first	1
        ///tenth	10
        ///hundredth	100
        ///thousandth	1000
        ///millionth	1000000
        ///billionth	1000000000
        ///eleventh	11
        ///twelfth	12
        ///thirteenth	13
        ///fourteenth	14
        ///fifteenth	15
        ///sixteenth	16
        ///seventeenth	17
        ///eighteenth	18
        ///nineteenth	19
        ///second	2
        ///twentieth	20
        ///two-hundredth	200
        ///twenty-first	21
        ///twenty-second	22
        ///twenty-third	23
        ///twenty-fourth	24
        ///twenty-fifth	25
        ///twenty-sixth	26
        ///twenty-seventh	27
        ///twenty-eighth	28
        ///twenty-ninth	29
        ///third	3
        ///thirtieth	30
        ///three-hundredth	300
        ///thirty-first	31
        ///thirty-second	32
        ///thirty-thir [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_en {
            get {
                return ResourceManager.GetString("manual_lemmatization_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primer	1
        ///primera	1
        ///primeras	1
        ///primero	1
        ///primeros	1
        ///décima	10
        ///décimas	10
        ///décimo	10
        ///décimos	10
        ///centésima	100
        ///centésimas	100
        ///centésimo	100
        ///centésimos	100
        ///milésima	1000
        ///milésimas	1000
        ///milésimo	1000
        ///milésimos	1000
        ///diezmilésima	10000
        ///diezmilésimas	10000
        ///diezmilésimo	10000
        ///diezmilésimos	10000
        ///cienmilésima	100000
        ///cienmilésimas	100000
        ///cienmilésimo	100000
        ///cienmilésimos	100000
        ///millonésima	1000000
        ///millonésimas	1000000
        ///millonésimo	1000000
        ///millonésimos	1000000
        ///diezmillonésima	10000000
        ///diezmi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_es {
            get {
                return ResourceManager.GetString("manual_lemmatization_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aabitsast	aabits
        ///aabitsat	aabits
        ///Aacheni	Aachen
        ///Aadama	Aadam
        ///Aadamale	Aadam
        ///Aadamast	Aadam
        ///aadete	aade
        ///aated	aade
        ///aadli	aadel
        ///aadlikuga	aadlik
        ///aadlimatrikli	aadlimatrikkel
        ///aadlimehe	aadlimees
        ///aadlisoost	aadlisoo
        ///aadlisoost	aadlisugu
        ///aadressi	aadress
        ///aadressid	aadress
        ///aadressiks	aadress
        ///aadressil	aadress
        ///aadressist	aadress
        ///aadressraamatuid	aadressraamat
        ///Aadul	Aadu
        ///Aadule	Aadu
        ///Aafrikale	Aafrika
        ///Aafrikas	Aafrika
        ///Aafrikast	Aafrika
        ///Aafrikat	Aafrika
        ///aafriklase	aafriklane
        ///aafriklased	aaf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_et {
            get {
                return ResourceManager.GetString("manual_lemmatization_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آيد	آ
        ///بيايي	آ
        ///آب‌ها	آب
        ///آپارتمانِ	آپارتمان
        ///بيام	آ
        ///آدرسِ	آدرس
        ///آپارتمان‌هايِ	آپارتمان
        ///آبجويِ	آبجو
        ///اواخرِ	آخر
        ///مي‌آيم	آ
        ///نيايد	آ
        ///آبِ	آب
        ///بياييم	آ
        ///بيا	آ
        ///مي‌آيد	آ
        ///آخرين	آخر
        ///آتش‌زدنِ	آتش‌زدن
        ///بياييد	آ
        ///آبي	آب
        ///آخرِ	آخر
        ///بيايد	آ
        ///آبيِ	آبي
        ///آب‌هايِ	آب
        ///اواخر	آخر
        ///بيايند	آ
        ///آچارهايي	آچار
        ///آبکيِ	آبکي
        ///آتشي	آتش
        ///آبي‌رنگِ	آبي‌رنگ
        ///بيايم	آ
        ///مي‌آيند	آ
        ///نمي‌آيد	آ
        ///آستين‌هايِ	آستين
        ///آمده	آمد
        ///آشنايي	آشنا
        ///آموخته	آموخت
        ///آگاهيِ	آگاهي
        ///آشوب‌هايِ	آشوب
        ///مي‌آمدند	آمد
        ///بياموزند	آموز
        ///آرايشگرِ	آرايشگر
        ///آدم‌ها	آدم
        ///آساي [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_fa {
            get {
                return ResourceManager.GetString("manual_lemmatization_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e	2e
        ///e	58e
        ///e	7e
        ///a jeun	à jeun
        ///à posteriori	a posteriori
        ///à priori	a priori
        ///abaissante	abaissant
        ///abaissée	abaissé
        ///abaissées	abaissé
        ///abaissés	abaissé
        ///abaissements	abaissement
        ///abaissa	abaisser
        ///abaissai	abaisser
        ///abaissaient	abaisser
        ///abaissais	abaisser
        ///abaissait	abaisser
        ///abaissâmes	abaisser
        ///abaissant	abaisser
        ///abaissas	abaisser
        ///abaissasse	abaisser
        ///abaissassent	abaisser
        ///abaissasses	abaisser
        ///abaissassiez	abaisser
        ///abaissassions	abaisser
        ///abaissât	abaisser
        ///abaissâtes	abaisser
        ///abaisse	abaisser        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_fr {
            get {
                return ResourceManager.GetString("manual_lemmatization_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aba	ab
        ///abaí	ab
        ///b&apos;ab	ab
        ///b&apos;abaí	ab
        ///d&apos;ab	ab
        ///d&apos;aba	ab
        ///d&apos;abaí	ab
        ///hab	ab
        ///haba	ab
        ///habaí	ab
        ///m&apos;ab	ab
        ///m&apos;aba	ab
        ///m&apos;abaí	ab
        ///n-ab	ab
        ///n-aba	ab
        ///n-abaí	ab
        ///t-ab	ab
        ///abacais	abacas
        ///b&apos;abacais	abacas
        ///b&apos;abacas	abacas
        ///d&apos;abacais	abacas
        ///d&apos;abacas	abacas
        ///habacais	abacas
        ///habacas	abacas
        ///m&apos;abacais	abacas
        ///m&apos;abacas	abacas
        ///n-abacais	abacas
        ///n-abacas	abacas
        ///t-abacas	abacas
        ///abachta	abacht
        ///b&apos;abacht	abacht
        ///d&apos;abacht	abacht
        ///d&apos;abachta	abacht
        ///habacht	abacht
        ///habachta	abacht
        ///m&apos;abacht	abacht
        ///m&apos;abachta	abacht
        ///n-abach [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ga {
            get {
                return ResourceManager.GetString("manual_lemmatization_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aba	ab
        ///abachan	ab
        ///abachan	aba
        ///abacasan	abacas
        ///abacais	abacas
        ///abachaidh	abachadh
        ///abaiche	abaich
        ///abaicheadh	abaich
        ///abaicheam	abaich
        ///abaicheamaid	abaich
        ///abaichear	abaich
        ///abaichibh	abaich
        ///abaichidh	abaich
        ///abaichinn	abaich
        ///abaichte	abaich
        ///abachadh	abaich
        ///abachaidh	abaich
        ///abaide	abaid
        ///abaidean	abaid
        ///abairte	abair
        ///abradh	abair
        ///abraibh	abair
        ///abram	abair
        ///abramaid	abair
        ///abrar	abair
        ///ràdh	abair
        ///teireadh	abair
        ///teireamaid	abair
        ///teirinn	abair
        ///their	abair
        ///theireadh	abair
        ///theireamaid	abair
        ///th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_gd {
            get {
                return ResourceManager.GetString("manual_lemmatization_gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as	a
        ///ás	á
        ///abas	aba
        ///abáboros	abáboro
        ///abacás	abacá
        ///bacelamentos	abacelamento
        ///abacela	abacelar
        ///abacelaba	abacelar
        ///abacelabades	abacelar
        ///abacelabamos	abacelar
        ///abacelaban	abacelar
        ///abacelabas	abacelar
        ///abacelaches	abacelar
        ///abacelada	abacelar
        ///abaceladas	abacelar
        ///abacelade	abacelar
        ///abacelades	abacelar
        ///abacelado	abacelar
        ///abacelados	abacelar
        ///abacelamos	abacelar
        ///abacelan	abacelar
        ///abacelando	abacelar
        ///abacelara	abacelar
        ///abacelará	abacelar
        ///abacelarades	abacelar
        ///abacelaramos	abacelar
        ///abacelaran	ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_gl {
            get {
                return ResourceManager.GetString("manual_lemmatization_gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa-aaseyn	aa-aase
        ///aa	aeg
        ///aachaignee	aachaignagh
        ///aachassidyn	aachassid
        ///aacheoidee	aacheoidagh
        ///aacheoidyn	aacheoid
        ///aacheyllaghaghyn	aacheyllaghey
        ///aachianglaghyn	aachiangley
        ///aachiangleagh	aachiangle
        ///aachianglee	aachiangle
        ///aachianglein	aachiangle
        ///aachiangle-jee	aachiangle
        ///aachianglemayd	aachiangle
        ///aachiangley	aachiangle
        ///aachiangleym	aachiangle
        ///aachiangleys	aachiangle
        ///aachianglit	aachiangle
        ///aachlashtynyn	aachlashtyn
        ///aachloiaghyn	aachloie
        ///aachooinaghtynyn	aachooinaghtyn
        ///aa-choorsalyn	aa-choors [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_gv {
            get {
                return ResourceManager.GetString("manual_lemmatization_gv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaronsonnak	Aaronson
        ///Aaronsont	Aaronson
        ///abbahagyni	abbahagy
        ///abbahagyta	abbahagy
        ///abbahagyták	abbahagy
        ///abbahagytam	abbahagy
        ///abbahagytuk	abbahagy
        ///abbamaradni	abbamarad
        ///abbamaradt	abbamarad
        ///Abbáziában	Abbázia
        ///ábécére	ábécé
        ///ablaka	ablak
        ///ablakában	ablak
        ///ablakából	ablak
        ///ablakai	ablak
        ///ablakaik	ablak
        ///ablakaikkal	ablak
        ///ablakainak	ablak
        ///ablakán	ablak
        ///ablakát	ablak
        ///ablakba	ablak
        ///ablakhoz	ablak
        ///ablakkal	ablak
        ///ablakok	ablak
        ///ablakokat	ablak
        ///ablakokba	ablak
        ///ablakokkal	ablak
        ///ablakokon	ablak
        ///ablak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_hu {
            get {
                return ResourceManager.GetString("manual_lemmatization_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abati	abate
        ///abbacchi	abbacchiare
        ///abbacchia	abbacchiare
        ///abbacchiai	abbacchiare
        ///abbacchiammo	abbacchiare
        ///abbacchiamo	abbacchiare
        ///abbacchian	abbacchiare
        ///abbacchiando	abbacchiare
        ///abbacchiano	abbacchiare
        ///abbacchiante	abbacchiare
        ///abbacchianti	abbacchiare
        ///abbacchiar	abbacchiare
        ///abbacchiaron	abbacchiare
        ///abbacchiarono	abbacchiare
        ///abbacchiasse	abbacchiare
        ///abbacchiasser	abbacchiare
        ///abbacchiassero	abbacchiare
        ///abbacchiassi	abbacchiare
        ///abbacchiassimo	abbacchiare
        ///abbacchiaste	abbacchiare
        ///abbacchiasti	a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_it {
            get {
                return ResourceManager.GetString("manual_lemmatization_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iodargírios	00
        ///aa	a
        ///aacheniana	aacheniano
        ///aachenianas	aacheniano
        ///aachenianos	aacheniano
        ///aais	aal
        ///aaleniana	aaleniano
        ///aalenianas	aaleniano
        ///aalenianos	aaleniano
        ///abas	aba
        ///abinha	aba
        ///abinhas	aba
        ///abita	aba
        ///abitas	aba
        ///ababás	ababá
        ///ababalhamentos	ababalhamento
        ///ababalha	ababalhar
        ///ababalhá	ababalhar
        ///ababalhada	ababalhar
        ///ababalhadas	ababalhar
        ///ababalhado	ababalhar
        ///ababalhados	ababalhar
        ///ababalhai	ababalhar
        ///ababalhais	ababalhar
        ///ababalham	ababalhar
        ///ababalhamo	ababalhar
        ///ababalhámo	ababalhar
        ///abab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_pt {
            get {
                return ResourceManager.GetString("manual_lemmatization_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.d.	a_dato
        ///abale	aba
        ///abalei	aba
        ///abalele	aba
        ///abalelor	aba
        ///abaua	aba
        ///abace	abac
        ///abacele	abac
        ///abacelor	abac
        ///abacul	abac
        ///abacului	abac
        ///abaca	abacă
        ///abace	abacă
        ///abacei	abacă
        ///abacele	abacă
        ///abacelor	abacă
        ///abagiţa	abagiţă
        ///abagiţe	abagiţă
        ///abagiţei	abagiţă
        ///abagiţele	abagiţă
        ///abagiţelor	abagiţă
        ///abagii	abagiu
        ///abagiii	abagiu
        ///abagiilor	abagiu
        ///abagiul	abagiu
        ///abagiului	abagiu
        ///abajurul	abajur
        ///abajurului	abajur
        ///abajururi	abajur
        ///abajururile	abajur
        ///abajururilor	abajur
        ///abandonul	abandon
        ///abandonulu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_ro {
            get {
                return ResourceManager.GetString("manual_lemmatization_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abakuse	abakus
        ///abakusmi	abakus
        ///abakusoch	abakus
        ///abakusom	abakus
        ///abakusov	abakus
        ///abakusu	abakus
        ///abakusy	abakus
        ///abatíš	abatiša
        ///abatišami	abatiša
        ///abatiše	abatiša
        ///abatiši	abatiša
        ///abatišiach	abatiša
        ///abatišiam	abatiša
        ///abatišou	abatiša
        ///abatišu	abatiša
        ///abažúre	abažúr
        ///abažúrmi	abažúr
        ///abažúroch	abažúr
        ///abažúrom	abažúr
        ///abažúrov	abažúr
        ///abažúru	abažúr
        ///abažúry	abažúr
        ///abbéami	abbé
        ///abbého	abbé
        ///abbém	abbé
        ///abbému	abbé
        ///abbéoch	abbé
        ///abbéom	abbé
        ///abbéov	abbé
        ///abbéovia	abbé
        ///Abcházca	Abcházec
        ///Abcházcam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_sk {
            get {
                return ResourceManager.GetString("manual_lemmatization_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niti	!niti
        ///predstavitelji	!predstavitelj
        ///Aaronsona	Aaronson
        ///Aaronsone	Aaronson
        ///Aaronsoni	Aaronson
        ///Aaronsonih	Aaronson
        ///Aaronsonom	Aaronson
        ///Aaronsonoma	Aaronson
        ///Aaronsonov	Aaronson
        ///Aaronsonu	Aaronson
        ///Abanki	Abanka
        ///Abebi	Abeba
        ///abecedi	abeceda
        ///abecednem	abeceden
        ///abecedni	abeceden
        ///abecednika	abecednik
        ///abecednike	abecednik
        ///abecedniki	abecednik
        ///abecednikih	abecednik
        ///abecednikom	abecednik
        ///abecednikoma	abecednik
        ///abecednikov	abecednik
        ///abecedniku	abecednik
        ///Abela	Abel
        ///Abrahamom	Abraham
        ///absolutn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_sl {
            get {
                return ResourceManager.GetString("manual_lemmatization_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A:et	A
        ///a:ets	a
        ///A:n	A
        ///a:na	a
        ///A:nas	A
        ///a:ns	a
        ///a:s	a
        ///A:t	A
        ///a:ts	a
        ///a-et	a
        ///A-ets	A
        ///A-n	A
        ///A-na	A
        ///a-nas	a
        ///A-ns	A
        ///a-s	a
        ///A-t	A
        ///a-ts	a
        ///ä:et	ä
        ///ä:ets	ä
        ///ä:n	ä
        ///ä:na	ä
        ///ä:nas	ä
        ///ä:ns	ä
        ///ä:s	ä
        ///ä:t	ä
        ///ä:ts	ä
        ///ä-et	ä
        ///ä-ets	ä
        ///ä-n	ä
        ///ä-na	ä
        ///ä-nas	ä
        ///ä-ns	ä
        ///ä-s	ä
        ///ä-t	ä
        ///ä-ts	ä
        ///å:et	å
        ///å:ets	å
        ///å:n	å
        ///å:na	å
        ///å:nas	å
        ///å:ns	å
        ///å:s	å
        ///å:t	å
        ///å:ts	å
        ///åar	å
        ///åarna	å
        ///åarnas	å
        ///åars	å
        ///å-et	å
        ///å-ets	å
        ///ån	å
        ///å-n	å
        ///å-na	å
        ///å-nas	å
        ///åns	å
        ///å-ns	å
        ///ås	å
        ///å-s	å
        ///å-t	å
        ///å-ts	å
        ///A3:s	A3
        ///a3s	a3
        ///a3-s	a3
        ///A4:s	A4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_sv {
            get {
                return ResourceManager.GetString("manual_lemmatization_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to абзаца	абзац
        ///абзацам	абзац
        ///абзацами	абзац
        ///абзацах	абзац
        ///абзаце	абзац
        ///абзаци	абзац
        ///абзаці	абзац
        ///абзаців	абзац
        ///абзацові	абзац
        ///абзацом	абзац
        ///абзацу	абзац
        ///абонента	абонент
        ///абонентам	абонент
        ///абонентами	абонент
        ///абонентах	абонент
        ///абоненте	абонент
        ///абоненти	абонент
        ///абоненті	абонент
        ///абонентів	абонент
        ///абонентові	абонент
        ///абонентом	абонент
        ///абоненту	абонент
        ///абсолютна	абсолютний
        ///абсолютная	абсолютний
        ///абсолютне	абсолютний
        ///абсолютнеє	абсолютний
        ///абсолютним	абсолютний
        ///абсолютними	абсолютний
        ///абсолют [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manual_lemmatization_uk {
            get {
                return ResourceManager.GetString("manual_lemmatization_uk", resourceCulture);
            }
        }
    }
}
